-- Keeps the original job posting text on the application, so it stays
-- available later for interview prep (until now only the generated CV/
-- letter were kept, not the offer that led to them).
-- A fresh install already gets this column from schema.sql.
ALTER TABLE applications ADD COLUMN offer_text TEXT;

-- Backfill: existing applications generated by a wizard job already have
-- the offer text sitting in wizard_jobs — recover it instead of leaving
-- those rows blank.
UPDATE applications
SET offer_text = (SELECT offer_text FROM wizard_jobs WHERE wizard_jobs.application_id = applications.id)
WHERE offer_text IS NULL
  AND EXISTS (SELECT 1 FROM wizard_jobs WHERE wizard_jobs.application_id = applications.id);
